### ISSUE TITLE
Add dependency targets

### ISSUE THREAD

**Issue by arschles** [arschles/pare#14]
Should be able to do this:

```toml
[targets]
    [targets.frontend]
        [targets.frontend.commands.webpack]
        exec = "webpack -w"
        crash = true
        directory = "frontend"
        [targets.frontend.commands.serve]
        exec = "make run"
        crash = true
        directory = "frontend"
    
    [targets.backend]
        [targets.backend.commands.test]
        exec = "go test ./..."
        crash = true
        directory = "backend"
        
        [targets.backend.commands.run]
        exec = "./run-server.sh"
        crash = true
        directory = "backend"

    [targets.everything]
        # this will run everything in the frontend and backend targets all concurrently
        # you can specify includes and define new commands to the 'everything' target
        include = ["frontend", "backend"]
```
