### ISSUE TITLE
Add a way to store variables

### ISSUE THREAD

**Issue by arschles** [arschles/pare#16]
For example, if you want to test a variety of different directories, it would be nice to store them in a single variable and use them over and over again. Here's an idea:

```toml
[variables]
    paths = "./path1 ./path2 ./path3"

[targets.target1.commands.command1]
    exec = "go test {{paths}}"
    crash = true

[targets.target1.commands.command2]
    exec = "go test {{paths}}"
    crash = true
```

The variable substitution syntax needs some thought, however, because I need to think about simplicity, understandability, and how good the error messages would be
