### ISSUE TITLE
Ability to run commands in a docker container?

### ISSUE THREAD

**Issue by arschles** [arschles/pare#18]
This is a big one, but would be nice for consistency's sake. 

From a user perspective, an individual command would go from this:

```toml
[targets.target1.commands.gotest]
        exec = "go test ./..."
        crash = true
```

To this:

```toml
[targets.target1.commands.gotest]
        exec = "go test ./..."
        crash = true
        docker-image = "quay.io/deis/go-dev:v1.6.0
        mount-to = "/go/src/github.com/arschles/pare"
        envs = {GOPATH: "/go"}
        working-dir = "/go/src/github.com/arschles/pare"
```
