### ISSUE TITLE
Allow users to serialize commands

### ISSUE THREAD

**Issue by arschles** [arschles/pare#20]
This is a big one. Some targets run daemons in commands (i.e. a local dev server), some run quick tasks in each command (i.e. a build), and some run a mix. For the ones that run quick tasks like a build, it might be nice to allow users to serialize commands. For example, a user might want to run jslint on their javascript before they compress it, but not compress it if the jslint failed.

One way to serialize commands might be to add a `dependencies` key to an individual command dictionary:

```toml
[targets.target1.commands.jslint]
    exec = "jslint ..."
    crash = true

[targets.target1.commands.compile-js]
    exec = "webpack"
    crash = true
```

## A note on `crash = true`

If a command has a dependency, the behavior of the command and the downstream command may change. 

### If the upstream specifies `crash = true` and it fails:

In this case, Pare will exit with code 1 as usual, but all downstreams won't begin execution.

### If the upstream specifies `crash = false` and it fails:

In this case, the program will not crash and all downstreams won't begin execution. Everything else will get a chance to execute, and, even if nothing else failed and specified `crash = true`, Pare will still exit with code 1. In this case, it will print out information on the dependency failure.
