### ISSUE TITLE
Enable targets

### ISSUE THREAD

**Issue by arschles** [arschles/pare#4]
Targets should be fairly simple to represent in toml:

```toml
[target1]
commands = ["echo a", "echo b"]

[target2]
commands = ["echo c", "echo d"]
```

Then, the CLI should be able to do this:

```console
pare run target1
```
